# Generated by Django 4.2.1 on 2023-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_roomfacility_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='roomsize',
            field=models.IntegerField(default=30),
        ),
    ]
