# Generated by Django 4.2.2 on 2023-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_roominfo_roomsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='img',
            field=models.TextField(),
        ),
    ]
